_target_: language_table.diffusion_reward_rl.rl.drqv2.agent.DrQV2Agent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: cuda
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: false
num_expl_steps: 2000
hidden_dim: 1024
feature_dim: 50
stddev_schedule: linear(1.0, 0.1, 3000000)
stddev_clip: 0.3